name: Automatic Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the first commit
        id: first_commit
        run: |
          if [[ $(git log --pretty=format:%H --no-merges | wc -l) -eq 1 ]]; then
            echo "::set-output name=is_first_commit::true"
          else
            echo "::set-output name=is_first_commit::false"
          fi
        shell: bash
          
      - name: Create Pull Request
        if: ${{ steps.first_commit.outputs.is_first_commit == 'true' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: branches } = await github.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/dev'
            });
            const branchExists = branches.length > 0;
            if (branchExists) {
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Automatically generated pull request',
                head: context.ref,
                base: 'dev',
                body: 'This pull request was automatically generated when pushing a new branch.'
              });
            } else {
              console.log('Branch "dev" does not exist.');
            }
